# Generated by Django 6.0.6 on 2026-06-09 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('system_down', 'System Down'), ('fm_outage', 'FM Station Outage'), ('security_breach', 'Security Breach'), ('infrastructure', 'Infrastructure Failure'), ('emergency', 'General Emergency'), ('data_breach', 'Data Breach'), ('fire', 'Fire / Evacuation'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('affected_systems', models.JSONField(default=list)),
                ('notified_emails', models.JSONField(default=list)),
                ('notified_phones', models.JSONField(default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ManyToManyField(blank=True, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='accounts.organisation')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FMStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=20)),
                ('heartbeat_url', models.URLField(blank=True, help_text='URL to ping for automatic status checking')),
                ('is_active', models.BooleanField(default=True)),
                ('alert_emails', models.TextField(blank=True, help_text='Comma-separated emails for alerts')),
                ('alert_phones', models.TextField(blank=True)),
                ('current_status', models.CharField(choices=[('on_air', 'On Air'), ('off_air', 'Off Air'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('total_uptime_today', models.IntegerField(default=0, help_text='Minutes on air today')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_stations', to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FMOutage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('down_at', models.DateTimeField()),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('auto_detected', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('alert_sent', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_outages_reported', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_outages_resolved', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='fm_report.fmstation')),
            ],
            options={
                'ordering': ['-down_at'],
            },
        ),
        migrations.CreateModel(
            name='FMHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='fm_report.fmstation')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
